#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”

ADD301_REDIRECT="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sudo apt-get update
sudo apt-get -y install nginx

mkdir /etc/nginx/html/
echo "Hello World" > /etc/nginx/html/index.html
sudo sed -i "53i $ADD301_REDIRECT" /etc/nginx/sites-available/default #add at line 53
sudo service nginx restart
