#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx

# create index page and webpage for error 404
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Get server's hostname
server_hostname=$(hostname)

# Configure Nginx
new_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
"

echo "$new_config" > /etc/nginx/sites-available/default

# Configure nginx.conf to add custom header
sed -i "/^\s*http {/a \ \ \ \ add_header X-Served-By $server_hostname;" /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart
