#!/usr/bin/env bash
# Script to listen to port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx stop &> /dev/null
service nginx status | grep -q "not running"

